create schema if not exists market;

set schema 'market';

create table if not exists items (
    id          bigint          generated by default as identity,
    title       varchar         not null,
    description varchar(2000)   not null,
    img_path    varchar         not null,
    price       bigint          not null,
    count       int             not null default 0,
    constraint pk_items primary key (id),
    constraint uk_items unique (title)
);

create table if not exists orders (
    id bigint generated by default as identity,
    constraint pk_orders primary key (id)
);

create table if not exists order_items (
    id          bigint          generated by default as identity,
    order_id    bigint          not null,
    item_id     bigint          not null,
    count       integer         not null,
    constraint pk_order_items primary key (id),
    constraint uk_order_items unique (order_id, item_id),
    constraint fk_order_items_item_id foreign key (item_id) references items(id),
    constraint fk_order_items_order_id foreign key (order_id) references orders(id)
);


--     *** some items ***
insert into items(title, description, img_path, price)
with src as (
    values
        ('Title 1', 'Some description 1', 'images/1.jpeg', 1),
        ('Title 2', 'Some description 2', 'images/2.jpeg', 2),
        ('Title 3', 'Some description 3', 'images/3.jpeg', 3),
        ('Title 4', 'Some description 4', 'images/4.jpeg', 4),
        ('Title 5', 'Some description 5', 'images/5.jpeg', 5)
)
select *
  from src
  where not exists(select 1 from items);