spring.application.name=my-market-app

## DB local
spring.r2dbc.url=r2dbc:h2:mem:///market_dev_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
spring.r2dbc.username=sa
spring.r2dbc.password=

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Log
logging.level.org.springframework.web=DEBUG
logging.level.reactor.netty.http.server=DEBUG
logging.level.org.springframework.validation=TRACE