spring.application.name=my-market-app

# PostgreSQL configuration
spring.r2dbc.url=${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/market?currentSchema=market}
spring.r2dbc.username=${SPRING_R2DBC_USERNAME:postgres}
spring.r2dbc.password=${SPRING_R2DBC_PASSWORD:password}

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
spring.liquibase.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/market?currentSchema=market}
spring.liquibase.user=${SPRING_DATASOURCE_USERNAME:postgres}
spring.liquibase.password=${SPRING_DATASOURCE_PASSWORD:password}