spring.application.name=my-market-app

# PostgreSQL configuration
spring.datasource.url=${MY_MARKET_DB_URL:jdbc:postgresql://localhost:5433/market?currentSchema=market}
spring.datasource.username=${MY_MARKET_DB_USER:postgres}
spring.datasource.password=${MY_MARKET_DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# init template data
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
