create table if not exists items (
    id              bigint generated by default as identity,
    title           varchar not null,
    description     varchar not null,
    img_path        varchar not null,
    price           bigint  not null,
    constraint pk_items primary key (id),
    constraint uq_items_title unique (title)
);

insert into items(title, description, img_path, price)
with recursive gen(num) as (
    select 1 as num
    where not exists(select 1 from ITEMS)
    union all
    select num + 1 as num
    from gen
    where num < 100
)
select 'Some title '||num, 'Some description '||num, 'images/'||(num+1) % 5 + 1||'.jpeg', num * 100
from gen;