create table if not exists items (
    id          bigint          generated by default as identity,
    title       varchar         not null,
    description varchar(2000)   not null,
    img_path    varchar         not null,
    price       bigint          not null,
    constraint pk_items primary key (id),
    constraint uk_items unique (title)
);

create table if not exists cart_items(
    item_id     bigint          not null,
    count       integer         not null,
    constraint pk_cart_items primary key (item_id)
);

create table if not exists orders (
    id bigint generated by default as identity,
    constraint pk_orders primary key (id)
);

create table if not exists order_items (
    id          bigint          generated by default as identity,
    order_id    bigint          not null,
    item_id     bigint          not null,
    count       integer         not null,
    constraint pk_order_items primary key (id),
    constraint uk_order_items unique (order_id, item_id),
    constraint fk_order_items_item_id foreign key (item_id) references items(id),
    constraint fk_order_items_order_id foreign key (order_id) references orders(id)
);